### ISSUE TITLE
Allow users to clean up generated trace files

### ISSUE THREAD

**Issue by classicwuhao** [classicwuhao/CycloneVSCodePlugin#4]
Once for a while, we should allow users to clean up generated trace files through menu `Clean Trace File`. This should clean up all trace files generated on a target platform.

**Comment by BastienTrc** [comment]
fixed in [aa180f2](https://github.com/classicwuhao/CycloneVSCodePlugin/commit/aa180f24fad2a75d56ddd9aa64fe2518a94f53c1)
